_extends: .github

repository:
  name: NucleosGDPRBundle
  description: ⚖️ This bundle provides a GDPR conform cookie information for symfony applications.
  homepage: https://nucleos.rocks
  topics: symfony, symfony-bundle, bundle, gdpr, dsgvo, sonata, sonata-block, blocker, privacy
